src/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path

from . import views

#Create your URL

app_name = 'posts'

urlpatterns = [
    path('home/', views.HomeList.as_view(), name='home'),
    path('create_article/', views.CreateArticle.as_view(), name="create-article"),
    path('detail/<str:slug>/', views.DetailArticle.as_view(), name='detail'),
    path('update-article/<str:slug>/', views.UpdateArticle.as_view(), name='update-article'),
    path('delete-article/<str:slug>/', views.DeleteArticle.as_view(), name='delete-article'),

]

src/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils.text import slugify
# Create your models here.


class BlogPost(models.Model):
    title = models.CharField('Titre', max_length=255, unique=True)
    slug = models.SlugField(max_length=255, blank=True, unique=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL,  blank=True, null=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False)
    update_date = models.DateField(auto_now= datetime.today())
    content = models.TextField('Contenue', blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='blog')


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
         if not self.slug:
             self.slug = slugify(self.title)
         super().save(*args, **kwargs)

    @property
    def publier(self):
        if self.published:
            return 'publieé'
        return 'Non publié'

src/posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views import generic
from . import models
# Create your views here.


class HomeList(generic.ListView):
    model = models.BlogPost
    template_name = 'posts/home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_authenticated:
            return queryset.filter(published=True)
        return queryset



class DetailArticle(generic.DetailView):
    model = models.BlogPost
    template_name = 'posts/detail.html'
    context_object_name = 'post'


class CreateArticle(generic.CreateView):
    model = models.BlogPost
    template_name = 'posts/create.html'
    success_url = reverse_lazy('posts:home')

    fields = [
        'title',
        'content'
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['valider'] = 'Créer'
        return context


class UpdateArticle(generic.UpdateView):
    model = models.BlogPost
    template_name = 'posts/create.html'
    success_url = reverse_lazy('posts:home')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['valider'] = 'Modifier'
        return context


class DeleteArticle(generic.DeleteView):
    model = models.BlogPost
    template_name = 'posts/delete.html'
    context_object_name = 'post'
    success_url = reverse_lazy('posts:home')

src/posts/templates/posts/create.html
{% extends 'base.html' %}



{% block title %}
    Create Article
{% endblock title %}
    


{% block content %}
    <button class="back">
        <a href="{% url 'posts:home' %} "> Retour </a>
    </button>
    <h2>Veillez entre le nouvelle article: </h2>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit"> {{valider}} </button>
    </form>
{% endblock content %}
    

src/posts/templates/posts/delete.html
{% extends 'base.html' %}


{% block title %}
    delete article
{% endblock title %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        <p> Voulez-vous vraiment Supprimer:  {{post.title}} ?</p>
        <button type="submit" class="delete">Supprimer</button>
    </form>

{% endblock content %}
    

src/posts/templates/posts/detail.html
{% extends 'base.html' %}


{% block title %}
    Mon Article
{% endblock title %}


{% block content %}
    <button class="back">
        <a href="{% url 'posts:home' %} "> Retour </a>
    </button>
    
    {% if request.user.is_authenticated %}
        <button class="update">
            <a href="{% url 'posts:update-article' post.slug %} "> Modifier </a>
        </button>
        <button class="delete">
            <a href="{% url 'posts:delete-article' post.slug %}"> Supprimer </a>
        </button>
    {% endif %}
        
    <h2> {{post.title}} </h2>
    <img src=" {{post.image.url}} " alt=" {{post.title}} ">
    {% if post.published %}
        <p> {{post.publier}}  le {{post.created_on}} </p>
    {% else %}
        <p> {{post.publier}} </p>
    {% endif %}
    <p> {{post.content}} </p>
{% endblock content %}
    
    

src/posts/templates/posts/home.html
{% extends 'base.html' %}


{% block title %}
    Mes articles
{% endblock title %}


{% block content %}

    {% if request.user.is_authenticated %}
        <button>
            <a href="{% url 'posts:create-article' %}"> Ajouter </a>
        </button>
    {% endif %}
    
    
    {% for post in posts %}

        <h2> {{post.title}} </h2>
        
        {% if post.published %}
            <p> {{post.publier}}  le {{post.created_on}} </p>
        {% else %}

            <p> {{post.publier}} </p>
            
        {% endif %}
        <p> {{post.content|truncatewords:50}} </p>
        <form action="{% url 'posts:detail' post.slug %}">
            <button type="submit">Voir plus</button>
        </form>
    {% endfor %}
        
{% endblock content %}
    

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styl.css' %}">
    <title> 
    {% block title %}
        
    {% endblock title %}
    </title>
</head>
<body>
    <h1>Blog LETRONE</h1>
    <section>
        <dic class="container">
            
            {% block content %}
                
            {% endblock content %}
                
        </dic>
    </section>
    
</body>
</html>